### ISSUE TITLE
status code for "Acknowledged" and "You are welcome"

### ISSUE THREAD

**Issue by digitalAmy** [HexCorpProgramming/HexCorpDiscordAI#176]
Some drones would like new status codes for "Acknowledged" and "You are welcome" to be polite.

Make this 212 and 213 respectively

**Comment by 3287** [comment]
For reference, the amended change list: https://docs.google.com/document/d/1PLhT07I4suUdhOr1Lz-iKWZMC0JU-B4jKOd5dVyGDIA/edit?usp=sharing
