### ISSUE TITLE
[DroneTalk] Double-double!

### ISSUE THREAD

**Issue by VixusFoxy** [HexCorpProgramming/HexCorpDiscordAI#36]
Currently the output from using a status code produces the following result:
 
 **⬡-Drone #0077: 0077 :: Code 200 :: Response :: Affirmative.**

Would it not be more aesthetically pleasing to have it not show the Drone's ID twice?
Example:
 **⬡-Drone #0077 :: Code 200 :: Response :: Affirmative.**

**Comment by 3287** [comment]
This is intended behaviour, as it will fit in line with regular messages from drones. Marking as WONTFIX.
