### ISSUE TITLE
Attempting to toggle identity enforcement before 2 weeks doesn't give a response

### ISSUE THREAD

**Issue by primis** [HexCorpProgramming/HexCorpDiscordAI#477]
Expected: "Access denied: you have not been on the server for long enough (...)"
Actual: The AI does not respond at all, nor does it take any action.
![image](https://github.com/user-attachments/assets/1e3e2176-59d5-42db-9b8b-a56eb88c4fcf)

**Comment by ZebraNorth** [comment]
Can't reproduce this, will need to look at it further.  It's possible that a message listener was handling the message before it ever got to processing the command.  For example, the command was issued from the channel drone-hive-assignment.

**Comment by ZebraNorth** [comment]
I still can't reproduce this.

**Comment by primis** [comment]
Confirmed just now that running a `hc!tei <id>` does work for me now, but it has been after 2 weeks in test server. Will leave/rejoin and test again

**Comment by ZebraNorth** [comment]
Replicated: Only happens when sending an image with no caption

**Comment by ZebraNorth** [comment]
Reproduced: The bug happens if the "hc!tei" message is deleted before the bot can reply to it, eg if identity enforcement is active.
