### ISSUE TITLE
Cannot delete bot messages by reacting with 🗑️

### ISSUE THREAD

**Issue by primis** [HexCorpProgramming/HexCorpDiscordAI#479]
Messages stick around, the bot does not delete them.
![image](https://github.com/user-attachments/assets/8b824122-bac6-445f-9014-0adaa5852734)

**Comment by ZebraNorth** [comment]
This is working for me, maybe you didn't have the hex drone role at the time?

**Comment by ZebraNorth** [comment]
It looks like it was due to the drone not having a properly associated database record, as tends to happen on the dev server.

**Comment by 3287** [comment]
Still broken even with a working database record:
![Image](https://github.com/user-attachments/assets/60bf56af-96c3-49ee-856a-13473772acfc)

**Comment by primis** [comment]
This is working now.
